openapi: 3.1.0
info:
  title: India Rescue Scraper API
  description: |
    Real-time updates on Indian Army and disaster rescue efforts from PIB, Sikkim.gov.in, NDTV, India Today, Times Now, and Twitter.
  version: 1.1.0
servers:
  - url: https://india-rescue-scraper.onrender.com
paths:
  /rescue-updates:
    get:
      operationId: fetchRescueUpdates
      summary: Get the latest updates about rescue missions in India.
      parameters:
        - name: query
          in: query
          required: true
          description: Keyword to filter updates (e.g. "sikkim", "rescue", "Sandhu")
          schema:
            type: string
      responses:
        '200':
          description: A list of real-time updates
          content:
            application/json:
              schema:
                type: object
                properties:
                  updates:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        summary:
                          type: string
                        source:
                          type: string
                        date:
                          type: string
                          format: date
                        url:
                          type: string
                          format: uri
        '204':
          description: No updates found
